import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider"; // ✅ make sure the path is correct
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
        <Provider> {/* ✅ Capitalized! */}
          {children}
        </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
